### ISSUE TITLE
Doesn't build on OS X

### ISSUE THREAD

**Issue by asmeurer** [bjodah/pybestprac#5]
```
Removing old work directory
Copying /Users/aaronmeurer/Documents/pybestprac to /Users/aaronmeurer/anaconda/conda-bld/work
Package: pybestprac--py34_0
source tree in: /Users/aaronmeurer/anaconda/conda-bld/work
+ /Users/aaronmeurer/anaconda/envs/_build/bin/python setup.py install
running install
running build
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-3.4
creating build/lib.macosx-10.5-x86_64-3.4/pybestprac
copying pybestprac/__init__.py -> build/lib.macosx-10.5-x86_64-3.4/pybestprac
copying pybestprac/norms.py -> build/lib.macosx-10.5-x86_64-3.4/pybestprac
creating build/lib.macosx-10.5-x86_64-3.4/pybestprac/util
copying pybestprac/util/__init__.py -> build/lib.macosx-10.5-x86_64-3.4/pybestprac/util
copying pybestprac/util/testing.py -> build/lib.macosx-10.5-x86_64-3.4/pybestprac/util
running build_ext
INFO:PCEExtension:Copying/rendering sources...
INFO:PCEExtension:Making dir: build/temp.macosx-10.5-x86_64-3.4
INFO:PCEExtension:Making dir: build/temp.macosx-10.5-x86_64-3.4/src/
DEBUG:PCEExtension:Copying src/euclid_enorm.f90 to build/temp.macosx-10.5-x86_64-3.4/src/euclid_enorm.f90
DEBUG:PCEExtension:Copying src/euclid.cpp to build/temp.macosx-10.5-x86_64-3.4/src/euclid.cpp
INFO:PCEExtension:Making dir: build/temp.macosx-10.5-x86_64-3.4/pybestprac/
DEBUG:PCEExtension:Copying pybestprac/_euclid.pyx to build/temp.macosx-10.5-x86_64-3.4/pybestprac/_euclid.pyx
INFO:PCEExtension:Copying build_files...
INFO:PCEExtension:In "build/temp.macosx-10.5-x86_64-3.4", executing:
"/Users/aaronmeurer/anaconda/bin/gfortran -c -std=f2008 -fPIC -Wall -Wextra -Wimplicit-interface -O3 -march=native -ffast-math -funroll-loops -o src/euclid_enorm.o -I/Users/aaronmeurer/anaconda/conda-bld/work/src src/euclid_enorm.f90"
Traceback (most recent call last):
  File "setup.py", line 126, in <module>
    setup(**setup_kwargs)
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/pycodeexport/dist.py", line 163, in run
    **ext.pycompilation_compile_kwargs
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/pycompilation/compilation.py", line 644, in compile_sources
    **file_kwargs
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/pycompilation/compilation.py", line 944, in src2obj
    runner.run()
  File "/Users/aaronmeurer/anaconda/envs/_build/lib/python3.4/site-packages/pycompilation/compilation.py", line 402, in run
    self.cmd_outerr))
pycompilation.util.CompilationError: Error executing '/Users/aaronmeurer/anaconda/bin/gfortran -c -std=f2008 -fPIC -Wall -Wextra -Wimplicit-interface -O3 -march=native -ffast-math -funroll-loops -o src/euclid_enorm.o -I/Users/aaronmeurer/anaconda/conda-bld/work/src src/euclid_enorm.f90' in build/temp.macosx-10.5-x86_64-3.4. Command exited with status 1 after givning the following output: /var/tmp//cchMElyQ.s:8:no such instruction: `vxorpd %xmm0, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:31:no such instruction: `vcvtsi2sd %ebx, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:36:no such instruction: `vcvtsi2sd %r8d, %xmm1,%xmm1'
/var/tmp//cchMElyQ.s:37:no such instruction: `vaddsd %xmm1, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:42:no such instruction: `vcvtsi2sd %r9d, %xmm2,%xmm2'
/var/tmp//cchMElyQ.s:43:no such instruction: `vaddsd %xmm2, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:48:no such instruction: `vcvtsi2sd %r10d, %xmm3,%xmm3'
/var/tmp//cchMElyQ.s:49:no such instruction: `vaddsd %xmm3, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:54:no such instruction: `vcvtsi2sd %r11d, %xmm4,%xmm4'
/var/tmp//cchMElyQ.s:55:no such instruction: `vaddsd %xmm4, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:60:no such instruction: `vcvtsi2sd %eax, %xmm5,%xmm5'
/var/tmp//cchMElyQ.s:61:no such instruction: `vaddsd %xmm5, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:66:no such instruction: `vcvtsi2sd %edx, %xmm6,%xmm6'
/var/tmp//cchMElyQ.s:67:no such instruction: `vaddsd %xmm6, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:72:no such instruction: `vcvtsi2sd %ebx, %xmm7,%xmm7'
/var/tmp//cchMElyQ.s:73:no such instruction: `vaddsd %xmm7, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:78:no such instruction: `vcvtsi2sd %r8d, %xmm8,%xmm8'
/var/tmp//cchMElyQ.s:79:no such instruction: `vaddsd %xmm8, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:94:no such instruction: `vmovdqa (%r11), %ymm9'
/var/tmp//cchMElyQ.s:99:no such instruction: `vpmulld %ymm9, %ymm9,%ymm10'
/var/tmp//cchMElyQ.s:100:no such instruction: `vextracti128 $0x1, %ymm10,%xmm11'
/var/tmp//cchMElyQ.s:101:no such instruction: `vcvtdq2pd %xmm10, %ymm13'
/var/tmp//cchMElyQ.s:102:no such instruction: `vcvtdq2pd %xmm11, %ymm12'
/var/tmp//cchMElyQ.s:103:no such instruction: `vaddpd %ymm13, %ymm12,%ymm1'
/var/tmp//cchMElyQ.s:111:no such instruction: `vmovdqa (%r9), %ymm14'
/var/tmp//cchMElyQ.s:114:no such instruction: `vpmulld %ymm14, %ymm14,%ymm15'
/var/tmp//cchMElyQ.s:115:no such instruction: `vextracti128 $0x1, %ymm15,%xmm2'
/var/tmp//cchMElyQ.s:116:no such instruction: `vcvtdq2pd %xmm15, %ymm4'
/var/tmp//cchMElyQ.s:117:no such instruction: `vcvtdq2pd %xmm2, %ymm3'
/var/tmp//cchMElyQ.s:118:no such instruction: `vaddpd %ymm4, %ymm3,%ymm5'
/var/tmp//cchMElyQ.s:119:no such instruction: `vaddpd %ymm5, %ymm1,%ymm1'
/var/tmp//cchMElyQ.s:121:no such instruction: `vmovdqa (%r9), %ymm6'
/var/tmp//cchMElyQ.s:124:no such instruction: `vpmulld %ymm6, %ymm6,%ymm7'
/var/tmp//cchMElyQ.s:125:no such instruction: `vextracti128 $0x1, %ymm7,%xmm8'
/var/tmp//cchMElyQ.s:126:no such instruction: `vcvtdq2pd %xmm7, %ymm10'
/var/tmp//cchMElyQ.s:127:no such instruction: `vcvtdq2pd %xmm8, %ymm9'
/var/tmp//cchMElyQ.s:128:no such instruction: `vaddpd %ymm10, %ymm9,%ymm11'
/var/tmp//cchMElyQ.s:129:no such instruction: `vaddpd %ymm11, %ymm1,%ymm1'
/var/tmp//cchMElyQ.s:131:no such instruction: `vmovdqa (%r9), %ymm12'
/var/tmp//cchMElyQ.s:135:no such instruction: `vpmulld %ymm12, %ymm12,%ymm13'
/var/tmp//cchMElyQ.s:136:no such instruction: `vextracti128 $0x1, %ymm13,%xmm14'
/var/tmp//cchMElyQ.s:137:no such instruction: `vcvtdq2pd %xmm13, %ymm2'
/var/tmp//cchMElyQ.s:138:no such instruction: `vcvtdq2pd %xmm14, %ymm15'
/var/tmp//cchMElyQ.s:139:no such instruction: `vaddpd %ymm2, %ymm15,%ymm3'
/var/tmp//cchMElyQ.s:140:no such instruction: `vaddpd %ymm3, %ymm1,%ymm1'
/var/tmp//cchMElyQ.s:143:no such instruction: `vmovdqa (%r9), %ymm4'
/var/tmp//cchMElyQ.s:146:no such instruction: `vmovdqa -96(%r9), %ymm11'
/var/tmp//cchMElyQ.s:147:no such instruction: `vpmulld %ymm4, %ymm4,%ymm5'
/var/tmp//cchMElyQ.s:148:no such instruction: `vpmulld %ymm11, %ymm11,%ymm12'
/var/tmp//cchMElyQ.s:149:no such instruction: `vextracti128 $0x1, %ymm5,%xmm6'
/var/tmp//cchMElyQ.s:150:no such instruction: `vcvtdq2pd %xmm5, %ymm8'
/var/tmp//cchMElyQ.s:151:no such instruction: `vcvtdq2pd %xmm6, %ymm7'
/var/tmp//cchMElyQ.s:152:no such instruction: `vaddpd %ymm8, %ymm7,%ymm9'
/var/tmp//cchMElyQ.s:153:no such instruction: `vextracti128 $0x1, %ymm12,%xmm13'
/var/tmp//cchMElyQ.s:154:no such instruction: `vcvtdq2pd %xmm12, %ymm15'
/var/tmp//cchMElyQ.s:155:no such instruction: `vcvtdq2pd %xmm13, %ymm14'
/var/tmp//cchMElyQ.s:156:no such instruction: `vaddpd %ymm15, %ymm14,%ymm2'
/var/tmp//cchMElyQ.s:157:no such instruction: `vaddpd %ymm9, %ymm1,%ymm10'
/var/tmp//cchMElyQ.s:158:no such instruction: `vmovdqa -64(%r9), %ymm1'
/var/tmp//cchMElyQ.s:159:no such instruction: `vpmulld %ymm1, %ymm1,%ymm4'
/var/tmp//cchMElyQ.s:160:no such instruction: `vaddpd %ymm2, %ymm10,%ymm3'
/var/tmp//cchMElyQ.s:161:no such instruction: `vmovdqa -32(%r9), %ymm10'
/var/tmp//cchMElyQ.s:163:no such instruction: `vpmulld %ymm10, %ymm10,%ymm11'
/var/tmp//cchMElyQ.s:164:no such instruction: `vextracti128 $0x1, %ymm4,%xmm5'
/var/tmp//cchMElyQ.s:165:no such instruction: `vcvtdq2pd %xmm4, %ymm7'
/var/tmp//cchMElyQ.s:166:no such instruction: `vcvtdq2pd %xmm5, %ymm6'
/var/tmp//cchMElyQ.s:167:no such instruction: `vaddpd %ymm7, %ymm6,%ymm8'
/var/tmp//cchMElyQ.s:168:no such instruction: `vextracti128 $0x1, %ymm11,%xmm12'
/var/tmp//cchMElyQ.s:169:no such instruction: `vcvtdq2pd %xmm11, %ymm14'
/var/tmp//cchMElyQ.s:170:no such instruction: `vcvtdq2pd %xmm12, %ymm13'
/var/tmp//cchMElyQ.s:171:no such instruction: `vaddpd %ymm8, %ymm3,%ymm9'
/var/tmp//cchMElyQ.s:172:no such instruction: `vaddpd %ymm14, %ymm13,%ymm15'
/var/tmp//cchMElyQ.s:173:no such instruction: `vaddpd %ymm15, %ymm9,%ymm1'
/var/tmp//cchMElyQ.s:176:no such instruction: `vhaddpd %ymm1, %ymm1,%ymm3'
/var/tmp//cchMElyQ.s:179:no such instruction: `vperm2f128 $1, %ymm3,%ymm3,%ymm2'
/var/tmp//cchMElyQ.s:180:no such instruction: `vaddpd %ymm2, %ymm3,%ymm1'
/var/tmp//cchMElyQ.s:181:no such instruction: `vaddsd %xmm1, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:183:no such instruction: `vzeroupper'
/var/tmp//cchMElyQ.s:190:no such instruction: `vcvtsi2sd %r11d, %xmm4,%xmm4'
/var/tmp//cchMElyQ.s:191:no such instruction: `vaddsd %xmm4, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:198:no such instruction: `vcvtsi2sd %r9d, %xmm5,%xmm5'
/var/tmp//cchMElyQ.s:199:no such instruction: `vaddsd %xmm5, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:206:no such instruction: `vcvtsi2sd %eax, %xmm6,%xmm6'
/var/tmp//cchMElyQ.s:207:no such instruction: `vaddsd %xmm6, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:214:no such instruction: `vcvtsi2sd %ebx, %xmm7,%xmm7'
/var/tmp//cchMElyQ.s:215:no such instruction: `vaddsd %xmm7, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:222:no such instruction: `vcvtsi2sd %ecx, %xmm8,%xmm8'
/var/tmp//cchMElyQ.s:223:no such instruction: `vaddsd %xmm8, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:230:no such instruction: `vcvtsi2sd %r10d, %xmm9,%xmm9'
/var/tmp//cchMElyQ.s:231:no such instruction: `vaddsd %xmm9, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:236:no such instruction: `vcvtsi2sd %esi, %xmm10,%xmm10'
/var/tmp//cchMElyQ.s:237:no such instruction: `vaddsd %xmm10, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:239:no such instruction: `vsqrtsd %xmm0, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:251:no such instruction: `vxorpd %xmm0, %xmm0,%xmm0'
/var/tmp//cchMElyQ.s:288:no such instruction: `vzeroupper'
```

**Comment by bjodah** [comment]
Thanks!

`-march=native` renderns AVX instructions which isn't supported by the assembler:
http://stackoverflow.com/questions/10327939/erroring-on-no-such-instruction-while-assembling-project-on-mac-os-x-lion

I will make this more robust.
